### ISSUE TITLE
Доработки по окну дубликатов

### ISSUE THREAD

**Issue by PetPython** [AndreiDrang/SimilarMemes#11]
**Краткое описание:**
1) Вызов окна дубликатов происходит по ячейке с непонятной буковкой 'D'.
2) Вызов окна дубликатов доступен абсолютно для всех файлов сразу же после прогона по кнопке 'Process media files'.
3) В окне дубликатов второй и третий столбец генерируют ячейки со словами 'Open folder' и 'Delete'.
4) В окне дубликатов отсутствует функционал открытия папки с файлом и его удаления.

**Необходимо:**
~~1) Заменить 'D' кнопкой с понятной иконкой (пример реализации см. [здесь](https://stackoverflow.com/questions/54316791/pyqt5-how-does-a-button-delete-a-row-in-a-qtablewidget-where-it-sits)).~~
2) Кнопка вызова окна дубликатов должна возникать после прогона по кнопке 'Find duplicates' и только для файлов, имеющих дубликат.
~~3) В окне дубликатов заменить указанные слова соответствующими кнопками с понятными иконками.~~
~~4) В окне дубликатов добавить на соответствующие кнопки функционал открытия папки с файлом и его удаления.~~
~~4.а) Запретить удаление оригинального файла, для которого открывается окно дубликатов.~~
~~4.b) Удаление файла должно удалять его не только из системы, но и из базы данных.~~
~~4.c) Если дубликат был удален из окна дубликатов, необходимо удалять и строку с ним в главном списке файлов.~~

**Comment by AndreiDrang** [comment]
1. С пунктом 2 в разделе "Необходимо" всё не так просто, ибо у нас начинается обращение к дубликатам картинки лишь после выбора её и нажатия на кнопку 'D', то есть до нажатия мы не знаем, есть ли дубликаты. Тут можно сделать так - жмём кнопку и если дубликатов нет, то и новое окно не появляется, а выводится предупреждение.
2. Пункт **4.с** реализуем, но тут два стула, либо список весь файлов надо будет пересобирать, после удаления файла из БД и системы, или как-то удалять файл из QT-таблицы по ID или каким-то ещё способом после нажатия кнопки удаления, тут я не знаю.
Всё остальное выглядит Ок.
P.s. Можешь ещё добавить один/два скрина того, как выглядит это сейчас, что бы понятно было куда и что переместится.
P.p.s. Я пока отложу реализацию подключения к локальной файловой БД т.к. туда надо будет сразу GUI прикрутить, что бы менять параметры.

**Comment by PetPython** [comment]
1. То есть пользователю нужно прокликать все картинки, чтобы найти дубликаты, которых, возможно, и нет вовсе? А если у него тысяча уникальных картинок? Нет, отметка о дубликате необходима в таблице сразу, иначе смысла во всем этом нет.
2. Удалить табличную строку проще простого.

**Comment by PetPython** [comment]
Сделаны 1, 3 и 4.
4а под вопросом, возможно, и не потребуется.
4с — как и было предсказано гуру — врезался в проблему определения нужного файла в общей таблице. По имени удалять нельзя, ибо будут повторяющиеся. Запомнить строку тоже не выйдет из-за наличия сортировки. Вариант вижу только один — добавление еще одного столбца с уникальным id по каждой строчке.

**Comment by AndreiDrang** [comment]
Круто!
>  Вариант вижу только один — добавление еще одного столбца с уникальным id по каждой строчке.

У нас у каждого изображения, в том числе и в паре, где дубликаты хранятся, есть их уникальные ID, которое не будут меняться от сортировки и т.д., можно ли как-то сделать удаление из списка по этому значению, что бы не вводить никаких дополнительных ID и т.п.? Что б как в СКЛе каком прямо -_-

**Comment by PetPython** [comment]
Я щас понял, что текущая работа таблицы косячная. Если взять два файла с одинаковым именем, лежащие в разных директориях, то после клика по любому из них, фактически будет открываться только первый файл (ибо берется первое вхождение из словаря). Потому что таблица не знает, какой у ячейки есть скрытый идентификатор. Текст ячейки и номер строки/столбца - это все, что она видит. По тексту — имени файла — ищется путь. А путей может быть несколько. Поэтому всегда вернется первый.
То есть все-таки нужен дополнительный столбец либо с id, либо сразу с путем до файла, чтобы программа понимала, чего от нее хотят. Как-то вот так.

**Comment by PetPython** [comment]
> То есть все-таки нужен дополнительный столбец либо с id

Сделано вместе с 4.c

**Comment by AndreiDrang** [comment]
За **4.b** берусь.
Добавлю удобный метод для кастомного удаления - чистит файл в БД и в системе.

**Comment by AndreiDrang** [comment]
**4.b** всё.
По **4.а** вопрос, по тому как, в принципе, для нас это не проблема. Ибо юзер хочет удалить главное изображение? Ок, удаляй, все пары с ним подчистились и окно закрыли.

**Comment by PetPython** [comment]
Да, я думал над таким вариантом. Если ты тоже согласен, то так и сделаем.

**Comment by AndreiDrang** [comment]
Okay, внесу такое

**Comment by PetPython** [comment]
Хотя вообще, если подумать, немного неправильно отображать строку главного изображения. Потому что юзер открывает окно ДУБЛИКАТОВ и видит какую-то строку в таблице. Логичная мысль — это дубликат. И удаляет его.
Поэтому-то я и хотел ввести запрет на удаление первой строчки, типа, чтобы юзер понимал, что это — главное изображение (и возможно, единственное), так что он его удалять наверняка не хочет.

Второй вариант: вообще не отображать строку с главным изображением, а только с дубликатами.

Просто на момент написания этого окна я туда помещал строку с главным изображением, чтобы хоть что-то видеть. Как образец.
Ну, либо третий вариант: при удалении первой строки выводить дополнительно: "You are trying to delete the source file (not a duplicate). Continue?"

**Comment by AndreiDrang** [comment]
Вот второй вариант хорош.
Я это окно доработал немного, чуть позже скрины могу скинуть.
И вообще хочу добавить вывод доп.инфы о изображении(типа реальных размеров/веса и т.д.) и вот это, я думаю, будет хорошо сочетаться со вторым твоим пунктом

**Comment by AndreiDrang** [comment]
Как-то так сейчас, буду ещё дорабатывать.
![Screenshot from 2019-06-13 20-20-54](https://user-images.githubusercontent.com/16991365/59453563-d6771b00-8e18-11e9-9f0e-2bf5f2395e36.png)

**Comment by PetPython** [comment]
K P A C U B O

**Comment by AndreiDrang** [comment]
N E D O S T A T O 4 N O
P.s. тут походу логику поиска дубликатов на спистон переписывать придется.

**Comment by AndreiDrang** [comment]
![Screenshot from 2019-06-18 21-26-29](https://user-images.githubusercontent.com/16991365/59709582-d3f93480-920f-11e9-8eeb-899f97e9b2c1.png)
![Screenshot from 2019-06-18 21-26-17](https://user-images.githubusercontent.com/16991365/59709583-d491cb00-920f-11e9-85ab-6569e1df4820.png)

Надо как-то жестко задать высоту верхнего блока с картинками, и если правая картинка больше левой - сжимать и выводить такой как получилось.
