### ISSUE TITLE
Рефакторинг. Изменить кусок логики при клике по ячейке

### ISSUE THREAD

**Issue by PetPython** [AndreiDrang/SimilarMemes#17]
**Необходимо:**
Исправить в **gui/main.py** повторяемый несколько раз кривой блок вида
`# Prevents from KeyError when clicking the second column:`
`    if imageItem.text() in ITEM_PATH_DICT:`

на вменяемое
`if column == 2:`

**Comment by AndreiDrang** [comment]
@PetPython Давай может названия для колонок введем этих? А то индексами не совсем понятно + мало ли когда меняться еще что будет в логике.

**Comment by PetPython** [comment]
Нельзя. Когда ты кликаешь по ячейке, в функцию типа
`show_image(self, row, column)`
передаются конкретные int'ы, равноценные координатам сетки. Ткнул в левую верхнюю ячейку — получил координаты **0;0**. Исходя из получаемых циферок можно уже писать условные операции. Что-то переименовывать выглядит безумным костылем.
Можно создать отдельный текстовый файлик типа
`0  | 1    | 2   | 3`
`id | name | ext | dupl_button`
чтобы вспоминать, что где находится.

**Comment by AndreiDrang** [comment]
@PetPython Ну я понимаю, да, что надо int передавать, просто можно в файле  настроек к gui задать имя_переменной = номер столбца и ими уже оперировать.

**Comment by AndreiDrang** [comment]
@AndreiDrang И можно будет менять/добавлять/изменять потом и т.д.

**Comment by PetPython** [comment]
Да, я только что об этом подумал, дополнительные глобалки типа int ввести.
Можно сделать, да.
_[но мне кажется, что одну циферку поставить проще]_

**Comment by AndreiDrang** [comment]
@PetPython Да, циферку проще, но я вот начал чекать gui недавно и было проблематично понять что и где.
Есть ещё выход - создавать все таблицы в одном месте. То есть вынести в функцию отдельную их создание и в неё только передавать параметры. Тогда можно и цифры оставить
