### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by AndreiDrang** [AndreiDrang/SimilarMemes#18]
**Is your feature request related to a problem? Please describe.**
Решить проблему с логированием ошибок при работе с программой.

**Describe the solution you'd like**
Добавить использование либо стандартной либы - `logging`, либо же кастомной - [logme](https://github.com/BNMetrics/logme).

**Comment by PetPython** [comment]
Стянул из своего собственного старого проекта, может, сгодится, если не хочется думать над всем этим. Ловит все. Модуль **logging**, ага.

```
# Логирование всевозможных непойманных ошибок. После ошибки программа закроется, а в папке с приложением создается лог с трейсбэком питоновского терминала

def error_message():
    error = QMessageBox()
    error.setIcon(QMessageBox.Critical)
    error.setWindowTitle('Критическая ошибка!')
    error.setText('Создан лог ошибки\nПрограмма будет завершена')
    error.setStandardButtons(QMessageBox.Ok)
    error.exec()
    sys.exit(app.exec_())

def log_exception(type, value, trace_back):
    currentWorkingDirectory = os.getcwd()
    logFileName = currentWorkingDirectory + '\\ERROR.log'
    logging.basicConfig(filename = logFileName)
    logging.critical(''.join(traceback.format_tb(trace_back)))
    logging.critical('{0}: {1}\n'.format(type, value))
    error_message()
 
# Собственно, пiйматель ошибок:
sys.excepthook = log_exception
```

**Comment by AndreiDrang** [comment]
Найс, это для GUI прикрутить надо.
А для остальной логики, прикрутил отдельный логер. Тогда его тоже на logging'e запилим.

**Comment by AndreiDrang** [comment]
#26 Добавл логер для бэка. Осталось для GUI прикрутить.
