### ISSUE TITLE
Добавить окно для `Matching settings`

### ISSUE THREAD

**Issue by AndreiDrang** [AndreiDrang/SimilarMemes#19]
**Is your feature request related to a problem? Please describe.**
Дать возможность юзерам вручную выбирать коэфициент схожести с которым будут идти рассчёты при определении дубликатов.

**Describe the solution you'd like**
Добавление полноценного окна со всеми настройками.

**Comment by PetPython** [comment]
Если хочешь, я могу создать новое окно, только скажи, что за ветка, и какой примерный вид. Типа единственное поле ввода интов от 0 до 100, рядом спинбокс "вверх-вниз"  или типа того.

**Comment by AndreiDrang** [comment]
Окей.
Значит ветка новая которая.
Окно с полем инта от 1 до 150, можно с кнопочками, можно без, как хочешь.
И выпадающий список(label - Matching Type) с вариантами(его пока никуда не пишем) - Feature, Histogram.

**Comment by PetPython** [comment]
Done
