### ISSUE TITLE
Вывод дополнительной информации о выбранном изображении

### ISSUE THREAD

**Issue by AndreiDrang** [AndreiDrang/SimilarMemes#23]
**Is your feature request related to a problem? Please describe.**
Одной из основных задач приложения, изначально, была очиста системы от дубликатов изображений. Сейчас дубликаты находятся номрально, но отсутствует удобнаый вывод информации о них.

**Describe the solution you'd like**
После последних обновлений в модель изображения была добавлена инфомация о реальных размерах (высота/ширина) изображения в системе. Теперь эту инфу надо выводить.
На скринах ниже красным обведены места, куда надо вставить текст с информацией о изображении. 
Для начала предлагаю выводить такую информацию:
1. ~~Полный путь к файлу, то есть папка+файл;~~ _Замена на возможность открыть изображение и папку с изображением_
1.1. ~~Добавить кнопку - открытие папки с этим изображением(возможно ли?)~~ Done
1.2. ~~И кнопку для копирования файла в буфер обмена(возможно ли?)~~ Done
1. ~~Размеры изображения `height x width`;~~

**Всё это надо и в окне дубликата и в окне с обычным предпросмотром изображения.**

![Screenshot from 2019-06-18 18-15-26](https://user-images.githubusercontent.com/16991365/59696770-50324e80-91f5-11e9-8637-4c0515f3d1e7.png)
![Screenshot from 2019-06-18 18-13-46](https://user-images.githubusercontent.com/16991365/59696771-50cae500-91f5-11e9-8acd-bd852ecd058c.png)

**Comment by PetPython** [comment]
Не понял по поводу 1.1. Там же есть иконка открытия папки с файлом. Или нужна папка именно оригинала?
1.2. В чем сакральный смысл копирования пути?
2: может, в виде дополнительного столбца?

**Comment by PetPython** [comment]
Вообще как насчет такой реализации? Все-таки оставляем строку с оригиналом, но помечаем ее понятным образом.
![123](https://user-images.githubusercontent.com/42939994/59707465-5a5f4780-920b-11e9-9f1f-0988df5f8991.png)

**Comment by AndreiDrang** [comment]
> Не понял по поводу 1.1. Там же есть иконка открытия папки с файлом. Или нужна папка именно оригинала?
Но он не работает -_- Всё забывал написать
> 1.2. В чем сакральный смысл копирования пути?
Скопировал и сразу вставил в ТГ, к примеру и отправляешь файл.
> 2: может, в виде дополнительного столбца?
Можно и так, но надо тогда таблицу будет переделать ибо сейчас не очень удобно.
Что бы она ресайзилась вместе с окном, а мы задавали только минимально возможную ширину столбца.
Это же и относится к главной таблице, ибо мммаксимум неудобно.

**Comment by AndreiDrang** [comment]
> Вообще как насчет такой реализации? Все-таки оставляем строку с оригиналом, но помечаем ее понятным образом.
> ![123](https://user-images.githubusercontent.com/42939994/59707465-5a5f4780-920b-11e9-9f1f-0988df5f8991.png)

Можно и такое, согласен, но это уже скорее к окну дубликатов относится, а не к выводу инфы.
