### ISSUE TITLE
Новые кнопки в GUI

### ISSUE THREAD

**Issue by AndreiDrang** [AndreiDrang/SimilarMemes#8]
**Is your feature request related to a problem? Please describe.**
Добавление кнопки для начала обработки(поиска дубликатов) фото/видео.
Добавление кнопки для начала проверки списка файлов/папок из БД на актуальность.

**Describe the solution you'd like**
Добавить две кнопки над таблице, на видном месте. Одна кнопка будет выполнять функцию обработки имеющихся фото/видео и выводить дубликаты, вторая кнопка будет проверять список файлов на наличие(если файлы были удалены из папок - удалять файлы из БД).

**Comment by PetPython** [comment]
Добавил первую кнопку ('Find duplicates').
Во второй не вижу смысла, ибо ее описанный функционал можно прикрутить к кнопке 'Process media files'.

**Comment by AndreiDrang** [comment]
Кнопка `Process media files` выполняет:
1. Проверку актуальности файлов и путей имеющихся в БД.
2. Проводит обновление и актуализацию файлов/папок из ФС.
